project:
  type: website

website:
  title: "Exploring Data with Jo"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/etc5523-2022/blog-jval0011
format:
  html:
    theme: minty
    css: styles.css



